spring:
  application:
    name: intelligent-farm-backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/intelligent_farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/**/*.xml


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


pagehelper:
  reasonable: true
  helper-dialect: mysql