spring:
  application:
    name: intelligent-farm-backend
  datasource:
    url: jdbc:mysql://localhost:3306/intelligent_farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug