server:
  port: 8080


spring:
  application:
    name: intelligent-farm-backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/intelligent_farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mqtt:
    username: nan # 用户名
    password: 123 # 密码
    url: tcp://broker.emqx.io:1883 # 连接地址
    subClientId: sub_client_id_123 # 订阅者客户端id
    subTopic: /mysmartagriculture/pub # 订阅的主题
    pubClientId: pub_client_id_123 # 发布者客户端id

#  server:
#    port: 8081
#  mqtt:
#    username: nan # 用户名
#    password: 123 # 密码
#    url: tcp://broker.emqx.io:1883 # 连接地址
#    subClientId: sub_client_id_123 # 订阅者客户端id
#    subTopic: /mysmartagriculture/pub # 订阅的主题
#    pubClientId: pub_client_id_123 # 发布者客户端id




mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/**/*.xml


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


pagehelper:
  reasonable: true
  helper-dialect: mysql